spring:
  application:
    name: barber-shop-api
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: nova_senha
  jpa:
    hibernate:
      ddl-auto: validate